"""initial schema

Revision ID: c65c8e682ecb
Revises: 
Create Date: 2025-07-31 17:11:11.448394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65c8e682ecb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('start_latitude', sa.Float(), nullable=True))
    op.add_column('rides', sa.Column('start_longitude', sa.Float(), nullable=True))
    op.add_column('rides', sa.Column('end_latitude', sa.Float(), nullable=True))
    op.add_column('rides', sa.Column('end_longitude', sa.Float(), nullable=True))
    op.add_column('rides', sa.Column('distance_km', sa.Float(), nullable=True))
    op.add_column('rides', sa.Column('estimated_duration', sa.Integer(), nullable=True))
    op.alter_column('rides', 'start_location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('rides', 'end_location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('rides', 'total_fare',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rides', 'total_fare',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('rides', 'end_location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('rides', 'start_location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('rides', 'estimated_duration')
    op.drop_column('rides', 'distance_km')
    op.drop_column('rides', 'end_longitude')
    op.drop_column('rides', 'end_latitude')
    op.drop_column('rides', 'start_longitude')
    op.drop_column('rides', 'start_latitude')
    # ### end Alembic commands ###