appium:
  server_url: "http://localhost:4723"  # Appium v2.x uses root URL, not /wd/hub
  implicit_wait: 10
  explicit_wait: 30
  
android:
  platform_name: "Android"
  automation_name: "UiAutomator2"
  # app_package: "host.exp.exponent"  # Expo Go package name (commented out for APK)
  # app_activity: (add if you know your app's main activity)
  app: "./CarpoolingApp.apk"  # Path to your APK file
  device_name: "Android Device"
  no_reset: true
  full_reset: false
  new_command_timeout: 300
  # auto_launch: false  # Not needed for APK
  dont_stop_app_on_reset: true
  skip_device_initialization: true
  skip_server_installation: true
  skip_unlock: true
  skip_log_capture: true

# Expo Go and navigation_urls removed for APK automation

test_data:
  valid_phone: "+1234567890"
  valid_email: "test@example.com"
  invalid_phone: "invalid"
  invalid_email: "invalid-email"
  
timeouts:
  short: 5
  medium: 10
  long: 30
  
screenshots:
  on_failure: true
  path: "screenshots/"