appium:
  server_url: "http://localhost:4723"  # Appium v2.x uses root URL, not /wd/hub
  implicit_wait: 10
  explicit_wait: 30
  
android:
  platform_name: "Android"
  automation_name: "UiAutomator2"
  # Connect to already running Expo Go app - NO launching
  app_package: "host.exp.exponent"  # Expo Go package name
  # Remove app_activity to avoid launching
  device_name: "Android Device"  # Will be auto-detected for physical device
  no_reset: true  # Don't reset the app
  full_reset: false
  new_command_timeout: 300
  # Connect to existing app capabilities
  auto_launch: false  # NEVER launch - only connect
  dont_stop_app_on_reset: true  # Keep app running
  skip_device_initialization: true  # Skip initialization 
  skip_server_installation: true
  # Additional no-launch settings
  skip_unlock: true
  skip_log_capture: true
  
test_data:
  valid_phone: "+1234567890"
  valid_email: "test@example.com"
  invalid_phone: "invalid"
  invalid_email: "invalid-email"
  
timeouts:
  short: 5
  medium: 10
  long: 30
  
screenshots:
  on_failure: true
  path: "screenshots/"